### ISSUE TITLE
How do I persist connection to BC?

### ISSUE THREAD

**Issue by kklon** [CoopBelvedere/laravel-basecamp-api#13]
Hey,
I'm trying to set this package up with my project. I got 0auth set up, I'm able to log in with BC, but then I'm not entirely sure how to use this package.
In Callback, in the sample project, we initialize Basecamp, then set cache/middleware, and then we're able to print out the projects available. This all works fine with my setup. 

I'm not sure though how to use this in real-life project, so I connect to BC once, and then can trigger api calls when I need them. Where should I initialize bootstrap, so I stay connected?

Sorry if it's a stupid question, but i'm pretty new to 0auth and spent far too long banging my head against a wall already

Would really appreciate some help, thanks.

**Comment by yuters** [comment]
I'm not totally sure if I understand your question but I'm going to try to answer.

You only have to do the OAuth thing once and you can reuse the same credentials including the access token. You need to save that in a database or in the session to keep the same connection active between requests to your app.

Also the Basecamp connection should persist during the request / response lifecycle of your app starting at the point where you call the `Basecamp::init()` function. Your best bet is to create a new middleware for it and use the app's session to retrieve your basecamp credentials. You could also make this check in the AppServiceProvider boot method if you don't need the session and you're only managing a single Basecamp account.
