### ISSUE TITLE
allow direct access to fetched collections (visibility private->public)

### ISSUE THREAD

**Issue by nekromoff** [CoopBelvedere/laravel-basecamp-api#17]
e.g. working with a collection is impossible:
```
$people = $basecamp->people()->index();

dd($people->items); // error: protected property

foreach ($people as $item) {
dd($item); //works, public
}
```

**Comment by yuters** [comment]
How would I solve this, and why?

The protected $items property is on the Collection class of Laravel itself, it has nothing to do with this package.

You can learn how to use Collections here: https://laravel.com/docs/8.x/collections

**Comment by nekromoff** [comment]
I can access other collections in Laravel directly, not just via a foreach
loop as individual items. So this is not a Laravel-related feature as
Laravel allows for direct access to the collections (e.g. I could access
$collection items directly using `->items` and work with it).

**Comment by yuters** [comment]
On a new Laravel install, I am unable to access `->items` on a new Collection object, so I'm not sure how you somehow do this.
To retrieve the $items property [which is protected in Laravel](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/Collection.php#L20), you would need to use the method `->all()`

If the $items property is originally public and I changed it to protected somewhere in my code, please show it to me and I'll fix it.
