### ISSUE TITLE
How to get an attachment from a comment?

### ISSUE THREAD

**Issue by vishalsaqbsolutions** [CoopBelvedere/laravel-basecamp-api#19]
Hi,

I want to use the attachments of comments. I am unable to load or download it because it has some authentication issue on the browser. I am getting the content of the comment as and also the src of the file or image But unable to use or download or use somewhere another place.

Is there a way to fetch that attachment so that it can be displayed with the comment elsewhere as well?

**Comment by yuters** [comment]
Can you provide the auth error?

**Comment by yuters** [comment]
I see you've got your answer on the bc3-api repo. For anyone else wondering, this isn't currently possible (Ref: https://github.com/basecamp/bc3-api/issues/215)
