### ISSUE TITLE
Multiple recording status types not working

### ISSUE THREAD

**Issue by Sunhat** [CoopBelvedere/laravel-basecamp-api#5]
Hi there

In the Basecamp API documentation, the Recording API allows you to pass multiple status types.

i.e.
`projects/recordings.json?type=active,trashed,archived`

However, when calling `->index("active,trashed,archived")` the commas get url encoded by GuzzleHttp.

`use \GuzzleHttp\Psr7\build_query;`

```
build_query(array_merge([
			'type' => $type,
                        'page' => $page
		], $parameters), false)
```

I'm not sure if this is applicable for any other requests, although, maybe I'm confused here, but this feature doesn't appear to be very good anyway. I think if you request with `?bucket=xxx&type=active,trashed` and there are no results for just one of the multiple status types passed, then you'll get an HTTP 4xx error

**Comment by yuters** [comment]
https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md

I can be mistaken but I'm guessing it's not actually a feature, I'm not seeing it in the documentation. You're right that it just returns an error if I try to query a comma delimited list of status even without url encoding.

Although, it looks like it's possible to have a comma delimited list of buckets. But I'd have to try with an upgraded plan to see if it works with url encoding or not. I'm keeping this open until then.

Thank you!

**Comment by Sunhat** [comment]
Hi, thats my bad! I got this all wrong... It's the bucket= that I meant. 

So if you request `?bucket=xxx,yyy&status=active` and if, for example, xxx **does** have results for active, but yyy **does not**, then you'll get an HTTP 4xx error.

**Comment by yuters** [comment]
Hey! :)

I've tried with multiple buckets, some with active tasks and other ones without. I'm not getting a 4xx error and everything seems fine. Maybe this was corrected on their end since then.

This is an example of how to query a delimited list of buckets:

```php
    $recordings = Basecamp::recordings()->index('Todo', [
        'bucket' => '100000,200000,300000',
        'status' => 'active',
        'sort' => 'created_at',
        'direction' => 'desc',
    ]);
```

Hope this helps!
